// <auto-generated />
using System;
using AiSchGeneratorApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiSchGeneratorApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306123143_AddSchematicSessions")]
    partial class AddSchematicSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiSchGeneratorApi.Models.SchematicHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CircuitJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("circuit_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("UserInput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_input");

                    b.HasKey("Id")
                        .HasName("pk_schematic_histories");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_schematic_histories_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_schematic_histories_user_id");

                    b.ToTable("schematic_histories", (string)null);
                });

            modelBuilder.Entity("AiSchGeneratorApi.Models.SchematicSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_schematic_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_schematic_sessions_user_id");

                    b.ToTable("schematic_sessions", (string)null);
                });

            modelBuilder.Entity("AiSchGeneratorApi.Models.SchematicHistory", b =>
                {
                    b.HasOne("AiSchGeneratorApi.Models.SchematicSession", "Session")
                        .WithMany("Histories")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_schematic_histories_schematic_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AiSchGeneratorApi.Models.SchematicSession", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
